### ISSUE TITLE
Project scaffolding

### ISSUE THREAD

**Issue by unnawut** [ReamLabs/ream#10]
This is a backtracking issue for the already-completed work on project scaffolding & CI setup.

- [x] Adding README (ReamLabs/ream#1)
- [x] Init rust project (ReamLabs/ream#2)
- [x] Add CI for rust (ReamLabs/ream#3)
- [x] Add clippy and rustfmt configs (ReamLabs/ream#6)
- [x] Add skeleton crates structure (ReamLabs/ream#7)
- [x] Add conventional commits ci (ReamLabs/ream#8)
- [x] Add basic cli parser (clap) (ReamLabs/ream#9)
