### ISSUE TITLE
meta: p2p stack prototyping

### ISSUE THREAD

**Issue by unnawut** [ReamLabs/ream#11]
Currently there's no networking specs for Beam, so we can just follow current CL network specs as we're in prototyping phase, and acknowledge that they could be totally changed in the actual Beam specs.

We can just use libp2p which solves a lot of networking part and later we can try to lift libp2p as there's huge chunk of code that we don't need.

## Acceptance criteria

- [ ] Client instances can discover each other via discv5 protocol
- [ ] Client instances can send/receive messages via gossipsub
- [ ] Able to demo a network simulation with 3 client instances

**Comment by KolbyML** [comment]
Closing as this issue is a little outdated, going to make a new issue re-organizing all the other issues
