### ISSUE TITLE
meta: State transition function snarkification

### ISSUE THREAD

**Issue by unnawut** [ReamLabs/ream#13]
This is the meta issue to track the CL's STF (state transition function) snarkification prototype.

## Acceptance criteria

- [ ] A zkVM backend is selected for client prototyping
- [ ] A client instance can prove minimal state transitions with the selected zkVM
    - Get current beacon state from a beacon testnet (or ephemery)
    - Listen for a new block from the beacon network
    - Snarkify block and slot processing
    - See the result (state root i guess?)
- [ ] The client instance can self-verify the proof
- [ ] The client is able to prove and verify every N blocks (N=125? Roughly 15 minutes)
- [ ] The codebase must be modular enough to easily switch to a different zkVM backend in the future

Additional: Justin mentioned preliminary work with hints could also be beneficial.

Additional - Also Justin's:

> Loading the full state is suboptimal. State reads and write are better to be done statelessly :)
>
> First load the state root. Then:
>
> * for reads: load the Merkle path from the leaf being read and authenticate the Merkle path to the state root
> * for writes: first read, then update the value, then remerkleise the Merkle path to get a new state root
>
> Some SSZ libraries should have all this implemented.

## References
- https://github.com/succinctlabs/sp1-helios - A wrapper project of helios(light client impl by a16z) by sp1, I thought developing CL version like this could work
- https://github.com/succinctlabs/sp1-reth
- See https://github.com/ethproofs/ethproofs for the current efforts to benchmark ZK proving of the execution layer

**Comment by KolbyML** [comment]
https://github.com/ReamLabs/ream/tree/master/crates/runtime

The zkVM's and abstraction should go in this area, we can make new crates likely within the runtime folder ad hoc.

I think it makes sense to support powdr and sp1 possing making an abstraction so we can choose which one we want to use. We can start with one zkVM starting out, then add support for another after.

**Comment by unnawut** [comment]
Just noting down for later recalls:

> While today generating a proof for an Ethereum block takes many minutes or hours, we know that there is no theoretical reason preventing massive parallelization: we can always put together enough GPUs to separately prove different parts of a block execution, and then use recursive SNARKs to put the proofs together. Additionally, hardware acceleration through FPGAs and ASICs could help optimize proving further. However, actually getting to this point is a significant engineering challenge that should not be underestimated. - https://notes.ethereum.org/@vbuterin/enshrined_zk_evm

Once sufficiently advanced enough we should look into how the proving work can be parallelized.

**Comment by unnawut** [comment]
Some notes from Justin:

> Loading the full state is suboptimal. State reads and write are better to be done statelessly
>
> no need to commit to the whole beacon state (except maybe once at genesis)
>
> First load the state root. Then:
>
> * for reads: load the Merkle path from the leaf being read and authenticate the Merkle path to the state root
> * for writes: first read, then update the value, then remerkleise the Merkle path to get a new state root
> 
> Some SSZ libraries should have all this implemented.

**Comment by syjn99** [comment]
Closing this issue as it's quite outdated, and we did some outputs like `consenzero-bench`. 
@x-senpai-x and @DimitriosMitsios might open a new issue regarding zkVM work on lean node.
